name: code-scheduler

on:
  schedule:
    - cron: "0 15 * * *"
  push:
    branches: [main]

jobs:
  code-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: post-code
        run: |
          curl -X POST ${{secrets.API_URL}}
